### ISSUE TITLE
IBC PDF is broken

### ISSUE THREAD

**Issue by okwme** [interchainio/ibcprotocol.org#10]
https://github.com/interchainio/ibcprotocol.org/blob/main/content/documentation/content.md tries to download the IBC PDF from here: https://github.com/cosmos/ics/blob/master/spec.pdf

the link fails to download, it might be a github large file bandwidth issue. We should upload it somewhere more accessible or figure out why github fails to allow downloads.

**Comment by gamarin2** [comment]
It works for me

**Comment by okwme** [comment]
weird it works from an incognito tab for me but not my logged in github account 🤔

**Comment by gamarin2** [comment]
I works well for me on a normal tab, and I'm also logged in (using firefox)

**Comment by okwme** [comment]
broken again but i think this time for real
links to https://media.githubusercontent.com/media/cosmos/ics/master/papers/2020-05/build/paper.pdf and https://github.com/cosmos/ics/raw/master/spec.pdf go nowhere

**Comment by lovincyrus** [comment]
Just checked if the PDFs are valid. They actually don't exist in the `cosmos/ics` → `cosmos/ibc` repo. The file structure has changed for the repo. But I found the PDFs from older commits.

1. https://github.com/cosmos/ibc/blob/302ba17ca8bc794e7d50afd9c6236d9c4e8e1230/archive/papers/2020-05/build/paper.pdf
2. https://github.com/cosmos/ibc/blob/302ba17ca8bc794e7d50afd9c6236d9c4e8e1230/archive/v0_3_1_IBC.pdf

Talked to Helder about deploying the static assets to an S3 bucket. 🆗 

Once we have them ready, I'll replace the URLs in the https://ibcprotocol.org/documentation

**Comment by helder-moreira** [comment]
They are ready now:

- https://s3.amazonaws.com/ibcprotocol.org/v0_3_1_IBC.pdf
- https://s3.amazonaws.com/ibcprotocol.org/paper.pdf

**Comment by lovincyrus** [comment]
> But I found the PDFs from older commits.

Can you confirm the PDFs are up to date? cc: @gamarin2 @okwme 

- https://s3.amazonaws.com/ibcprotocol.org/v0_3_1_IBC.pdf
- https://s3.amazonaws.com/ibcprotocol.org/paper.pdf

**Comment by okwme** [comment]
The first one was the origina from 2017 and the second one is the relevant one. I asked @cwgoes about the second missing link and he said:
> I actually removed the single PDF as it makes less sense with the updated spec structure IMO

then asked:
> Do you think a lot of people were reading that?

I don't know the answer as I don't fully understand the difference between the two links. Maybe chris can make a final call?

**Comment by lovincyrus** [comment]
> Maybe chris can make a final call?

Definitely.

Shall we do something with [the broken links](https://ibcprotocol.org/documentation) in the meantime? We should merge this https://github.com/interchainio/ibcprotocol.org/pull/11 and update anything else later on.

**Comment by okwme** [comment]
I don't think we want the version from 2017 but i could be wrong...
maybe just replacing the one is ok?
https://github.com/interchainio/ibcprotocol.org/pull/12

**Comment by cwgoes** [comment]
We definitely shouldn't use old versions. I can update the PDF if people found it useful.

**Comment by gamarin2** [comment]
>We definitely shouldn't use old versions. I can update the PDF if people found it useful.

Yes please! We need this asap to put the pdf back on the website 🙏
